{
    'name': 'Check Printing Management',
    'version': '18.0.1.0',
    'summary': 'Print checks with layout support',
    'description': 'Custom check printing with layout and accounting integration.',
    'author': 'Net4X Innovation',
    'website': 'https://net4x-innovation.com/',
    'license': 'LGPL-3',
    'category': 'Accounting',
    'depends': ['account', 'mail', 'account_check_printing'],
    'data': [
        'security/ir.model.access.csv',
        'views/check_layout_views.xml',
        'views/check_layout_wizard_view.xml',
        'views/account_payment_views.xml',
        'report/report_check_template.xml',
        'report/report_action.xml',
    ],
    'installable': True,
    'application': False,
}
